### PR TITLE
Changed to support openGL by default

### PR DESCRIPTION
**Pull request by L-shoe**
If you don't want to use openGL, I would appreciate an explanation as I'm trying to figure out the downsides of using it. Thanks very much for this project!

### CODE REVIEW

**Comment by Mat2095** [comment]
Good question, that line of code is more than three years old. I assume there are issues on linux, as another project of mine contains the same line but there I added a comment "just in case... OpenGL causes major glitches on Linux". I don't remember what these glitches are.

I just tested it on my linux-machine and didn't see any problems. I guess i was refering to the machines at my university, which have quite old drivers. I'll check tomorrow if I'll get glitches there. If its just because of the drivers, I guess I could remove that line.

Are you using windows or linux? Do you get a benefit from activating OpenGL (e.g. performance)?

**Comment by L-shoe** [comment]
Funnily enough I tested it on my university's  Linux machines and experienced an FPS boost from 12fps to 60

Will install Windows on my laptop when I'm at home and see what happens in that scenario, and will try on a beefier machine with Windows too.

I can see uni drivers being an issue haha. I'll update my PR to see if there's any way to toggle opengl mode or something to that effect in the event that users do experience issues :)

**Comment by Mat2095** [comment]
On windows I noticed no difference, I always get 60fps, no matter what I choose for opengl and direct3d.

On my linux machine I got a boost as well, but only from 10 to 25fps.

Users should be able to change the engine with some parameters: https://docs.oracle.com/javase/7/docs/technotes/guides/2d/flags.html

**Comment by Mat2095** [comment]
Okay, on the university machines I got a boost from 20-30 to 50-60, with no glitches. So, unless you get problems on windows, I'd merge the PR.

The glitches in the other project are still there when using opengl (something with bufferedimage having a limited size, but MySlither doesn't use those features).
In case you're interested, that project should look like this:
Bildschirmfoto von 2019-10-16 11-00-07
But using opengl results in this:
Bildschirmfoto von 2019-10-16 11-00-23

**Comment by L-shoe** [comment]
Oh wow, that is weird artefacting indeed

Yeah I experienced same as you, 60fps regardless on Windows 10 with a 2060.

If you want to merge then go right ahead, I'm gonna have a play around to see if I can find any other interesting properties

**Comment by Mat2095** [comment]
I've noticed there are quite a lot of forks by students from the university of Lancaster. Some PDF said something about a workshop / group project 210; could you tell me what's going on? This seems quite interesting ^^

**Comment by L-shoe** [comment]
One of the intro projects for working in groups is to add features and adjustments to somebody else's github projects, as lots of students have a mentality of "I'll do it myself instead" which falls apart when working in groups.

Looks like lots of people are interested in using your slither project, which would explain the forks

**Comment by Mat2095** [comment]
Ah cool, thanks for the info!

**Pull request merged**
